/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * This is a modular STM32 project that uses:
  * - Keypad
  * - LCD
  * - IR Remote
  * - System Access (password check)
  * - Motor Driver (fan/light control)
  * - EEPROM (data storage)
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx_hal.h"
#include "keypad.h"
#include "lcd.h"
#include "ir_remote.h"
#include "system_access.h"
#include "motor_driver.h"
#include "eeprom.h"

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);

/* USER CODE BEGIN 0 */
char password[5] = "1234";
/* USER CODE END 0 */

int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();

  /* Initialize peripherals */
  LCD_Init();
  Keypad_Init();
  IR_Init();
  MotorDriver_Init();
  EEPROM_Init();
  SystemAccess_Init();

  LCD_Clear();
  LCD_SendString("Smart Home Ready");

  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* --- Example 1: Check keypad input --- */
    char key = Keypad_GetKey();
    if (key != '0') {
      LCD_Clear();
      LCD_SendString("Key Pressed: ");
      char msg[2] = {key, '\0'};
      LCD_SendString(msg);
    }

    /* --- Example 2: IR Remote input --- */
    uint32_t ir_code = IR_ReadCode();
    if (ir_code != 0) {
      LCD_Clear();
      LCD_SendString("IR Code: ");
      // Just a placeholder
    }

    /* --- Example 3: Motor control --- */
    MotorDriver_Forward();
    HAL_Delay(1000);
    MotorDriver_Stop();
    HAL_Delay(1000);

    /* --- Example 4: EEPROM store & read --- */
    EEPROM_Write(0x10, 0x55);
    uint8_t data = EEPROM_Read(0x10);
    if (data == 0x55) {
      LCD_Clear();
      LCD_SendString("EEPROM OK");
    }

    HAL_Delay(2000);
  }
  /* USER CODE END WHILE */
}

/* System Clock Configuration */
void SystemClock_Config(void)
{
  // Auto-generated by CubeMX (keep as is for now)
}

/* GPIO Initialization Function */
static void MX_GPIO_Init(void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  // Add your pin configs here
}
